drop index  IDX_R4_TV if exists;
drop index  IDX_R4_VSI if exists;
drop index  IDX_VR4_VB if exists;
drop view   vr4  if exists;

drop index  IDX_VR4_IDV if exists;
drop index  IDX_VR4_VMB if exists;
drop table  r4  if exists;

DROP INDEX IDX_R21_TINY IF EXISTS;
DROP INDEX IDX_R21_BIG  IF EXISTS;
DROP INDEX IDX_R21_DEC  IF EXISTS;
DROP INDEX IDX_R21_VIM  IF EXISTS;
DROP INDEX IDX_R21_TIME IF EXISTS;
DROP INDEX IDX_R21_VBIN IF EXISTS;
DROP INDEX IDX_R21_POLY IF EXISTS;
drop table  r21 if exists;

CREATE TABLE R4 (
  ID      INTEGER  DEFAULT 0,
  TINY    TINYINT  DEFAULT 0,
  SMALL   SMALLINT DEFAULT 0,
  INT     INTEGER  DEFAULT 0,
  BIG     BIGINT   DEFAULT 0,
  NUM     FLOAT    DEFAULT 0,
  DEC     DECIMAL  DEFAULT 0,
  VCHAR_INLINE      VARCHAR(14)       DEFAULT '0',
  VCHAR_INLINE_MAX  VARCHAR(63 BYTES) DEFAULT '0',
  VCHAR_OUTLINE_MIN VARCHAR(64 BYTES) DEFAULT '0' NOT NULL,
  VCHAR             VARCHAR           DEFAULT '0',
  VCHAR_JSON        VARCHAR(1000)     DEFAULT '0',
  TIME    TIMESTAMP       DEFAULT '2013-10-30 23:22:29',
  VARBIN  VARBINARY(100)  DEFAULT x'00',
  -- Default values of GEOGRAPHY_POINT and GEOGRAPHY not supported (ENG-12028)
  POINT   GEOGRAPHY_POINT,
  POLYGON GEOGRAPHY,
  -- Used to test internet address functions:
  -- INET6_ATON, INET6_NTOA, INET_ATON, INET_NTOA
  IPV4    VARCHAR(15),
  IPV6    VARCHAR(60),
  VBIPV4  VARBINARY(4),
  VBIPV6  VARBINARY(16),
  PRIMARY KEY (ID, VCHAR_OUTLINE_MIN)
);
-- Will not work with SqlCoverage/PostgreSQL (2 lines):
CREATE UNIQUE INDEX IDX_R4_TV  ON R4 (TINY, VCHAR);
CREATE UNIQUE INDEX IDX_R4_VSI ON R4 (VCHAR, SMALL, INT);

CREATE VIEW VR4 (VCHAR, BIG,
ID, TINY, SMALL, INT, NUM, DEC,
VCHAR_INLINE, VCHAR_INLINE_MAX, VCHAR_OUTLINE_MIN, VCHAR_JSON, TIME
-- Will not work with SqlCoverage/PostgreSQL:
, VARBIN, POINT, POLYGON
, IPV4, IPV6, VBIPV4, VBIPV6
) AS
SELECT VCHAR, BIG,
COUNT(*), SUM(TINY), MAX(SMALL), COUNT(VCHAR_INLINE_MAX), MAX(NUM), MIN(DEC),
MAX(VCHAR_INLINE), MIN(VCHAR_INLINE_MAX), MAX(VCHAR_OUTLINE_MIN), MIN(VCHAR_JSON), MAX(TIME)
-- Will not work with SqlCoverage/PostgreSQL:
, MIN(VARBIN), MAX(POINT), MIN(POLYGON)
, MAX(IPV4), MIN(IPV6), MAX(VBIPV4), MIN(VBIPV6)
FROM R4 WHERE VCHAR_INLINE < 'N'
GROUP BY VCHAR, BIG;
CREATE INDEX IDX_VR4_VB  ON VR4 (VCHAR, BIG)             WHERE BIG >= 0;
CREATE INDEX IDX_VR4_IDV ON VR4 (INT, DEC, VCHAR_INLINE) WHERE VCHAR_INLINE < 'a';
CREATE INDEX IDX_VR4_VMB ON VR4 (VCHAR_INLINE_MAX, BIG)  WHERE BIG >= 0 AND VCHAR_INLINE_MAX IS NOT NULL;

CREATE TABLE R21 (
  ID      INTEGER NOT NULL,
  TINY    TINYINT,
  SMALL   SMALLINT,
  INT     INTEGER,
  BIG     BIGINT,
  NUM     FLOAT,
  DEC     DECIMAL,
  VCHAR_INLINE      VARCHAR(14),
  VCHAR_INLINE_MAX  VARCHAR(63 BYTES),
  VCHAR_OUTLINE_MIN VARCHAR(64 BYTES),
  VCHAR             VARCHAR,
  VCHAR_JSON        VARCHAR(1000),
  TIME    TIMESTAMP,
  VARBIN  VARBINARY(100),
  POINT   GEOGRAPHY_POINT,
  POLYGON GEOGRAPHY,
  -- Used to test internet address functions:
  -- INET6_ATON, INET6_NTOA, INET_ATON, INET_NTOA
  IPV4    VARCHAR(15),
  IPV6    VARCHAR(60),
  VBIPV4  VARBINARY(4),
  VBIPV6  VARBINARY(16),
  PRIMARY KEY (ID)
);

CREATE INDEX IDX_R21_TINY ON R21 (TINY);
CREATE INDEX IDX_R21_BIG  ON R21 (BIG);
CREATE INDEX IDX_R21_DEC  ON R21 (DEC);
CREATE INDEX IDX_R21_VIM  ON R21 (VCHAR_INLINE_MAX);
CREATE INDEX IDX_R21_TIME ON R21 (TIME);
CREATE INDEX IDX_R21_VBIN ON R21 (VARBIN);
CREATE INDEX IDX_R21_POLY ON R21 (POLYGON);
-- Define "standard" DDL (tables, indexes, views), for use with the SQL grammar generator

CREATE TABLE R3 (
  ID      INTEGER NOT NULL,
  TINY    TINYINT,
  SMALL   SMALLINT,
  INT     INTEGER,
  BIG     BIGINT,
  NUM     FLOAT,
  DEC     DECIMAL,
  VCHAR_INLINE      VARCHAR(42 BYTES),
  VCHAR_INLINE_MAX  VARCHAR(15),
  VCHAR_OUTLINE_MIN VARCHAR(16),
  VCHAR             VARCHAR,
  VCHAR_JSON        VARCHAR(4000 BYTES),
  TIME    TIMESTAMP,
  VARBIN  VARBINARY(100),
  POINT   GEOGRAPHY_POINT,
  POLYGON GEOGRAPHY,
  -- Used to test internet address functions:
  -- INET6_ATON, INET6_NTOA, INET_ATON, INET_NTOA
  IPV4    VARCHAR(15),
  IPV6    VARCHAR(60),
  VBIPV4  VARBINARY(4),
  VBIPV6  VARBINARY(16),
  PRIMARY KEY (VCHAR)
  -- Will not work with SqlCoverage/PostgreSQL (2 lines):
  , CONSTRAINT IDX_R3_TV  UNIQUE (TINY, VCHAR)
  , CONSTRAINT IDX_R3_VSI UNIQUE (VCHAR_INLINE, INT, NUM)
);
